version: "3"
services:
  rabbitmq-service:
    image: "rabbitmq:management"
    ports:
      - "5672:5672"
      - "15672:15672"
  data-service:
    build: ./data-service
    depends_on:
      - rabbitmq-service
  webhook-service:
    build: ./webhook-service
    depends_on:
      - rabbitmq-service
  inventory-service:
    build: ./inventory-service
    ports:
      - "5002:5002"
    depends_on:
      - rabbitmq-service
  shipping-service:
    build: ./shipping-service
    ports:
      - "5000:5000"
    depends_on:
      - rabbitmq-service
      - billing-service
  users-service:
    build: ./users-service
    ports:
      - "5008:5008"
    depends_on:
      - rabbitmq-service
  billing-service:
    build: ./billing-service
    ports:
      - "5001:5001"
    depends_on:
      - rabbitmq-service
